### ISSUE TITLE
when trying to get any book it says " no working mirrors available to download book " 

### ISSUE THREAD

**Issue by genijuf** [dstark5/Openlib#87]
when trying to get any book on openlib it would say  " no working mirrors available to download book " i tried uninstalling the app and then installing it back several times tried getting it from obtainium and latest release but no help it has same problems as #66 but they say on the new version its fixed meanwhile its actually not i also tried doing that with proton vpn and without proton vpn i use graphene os on a google pixel 8

**Comment by hansgruberle** [comment]
also having this issue

**Comment by Allastratou** [comment]
I believe it's due to the way they've recently changed how books are downloaded from the free "slow" servers on Annas-Archive itself. There's a 300-ish second wait before the download button becomes available, so maybe the app doesn't handle that properly? Only thing to do for now is visit the site itself and download normally, I imagine.

**Comment by dstark5** [comment]
Hi 👋 ,
This is caused due to a change in Anna's archive website they made a 120 seconds wait time to get the download link will try to fix it ASAP.

**Comment by dstark5** [comment]
Hi 👋,
This issue is fixed in latest 1.0.7 build.
Thank you
